# Generated by Django 2.2.6 on 2019-10-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='value',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
